// packages/svelte/src/app/menu/Menu.svelte
<script lang="ts">
  import { style } from 'core/style'
  import { onMount, setContext } from 'svelte'
  import { useStopwatch } from '~/lib/hooks'
  import { state } from '~/store'
  import Autosolve from './Autosolve.svelte'
  import ColorMode from './ColorMode.svelte'
  import Edit from './Edit.svelte'
  import Help from './Help.svelte'
  import StartOver from './StartOver.svelte'
  import Timer from './Timer.svelte'

  const stopwatch = useStopwatch()
  const { isRunning } = stopwatch
  const { isSolved } = state
  setContext('stopwatch', stopwatch)
  onMount(stopwatch.startTimer)
  $: {
    if ($isSolved && $isRunning) {
      stopwatch.stopTimer()
    }
  }
</script>

<div class={style.menu.root}>
  <Timer />
  <div class={style.menu.btns.root}>
    <StartOver />
    <Edit />
    <Autosolve />
    <ColorMode />
    <Help />
  </div>
</div>

// packages/solid/src/App/Menu/index.tsx
import { style } from 'core/style'
import { useStopwatch } from '~/lib/hooks'
import { state } from '~/store'
import Autosolve from './Autosolve'
import ColorMode from './ColorMode'
import Edit from './Edit'
import Help from './Help'
import StartOver from './StartOver'
import Timer from './Timer'
import { createEffect, onMount } from 'solid-js'

const _ = () => {
  const stopwatch = useStopwatch()
  onMount(stopwatch.startTimer)
  createEffect(() => {
    if (!state.isSolved) return
    if (!stopwatch.isRunning()) return
    stopwatch.stopTimer()
  })
  return (
    <div class={style.menu.root}>
      <Timer stopwatch={stopwatch} />
      <div class={style.menu.btns.root}>
        <StartOver />
        <Edit />
        <Autosolve />
        <ColorMode />
        <Help />
      </div>
    </div>
  )
}

export default _
