// packages/vue/src/lib/components/modal.vue
<script setup lang="ts">
import {
  type Dialog,
  inBounds,
} from 'core/lib/components/modal'
import { IO } from 'fp-ts/IO'
import { effect, inject, type Ref, ref } from 'vue'

interface Props {
  className?: string
  onClose: IO<void>
}
const { className, onClose } = defineProps<Props>()
const isOpen: Ref<boolean> | undefined = inject('isOpen')
let modal = ref(null) as unknown as Ref<Dialog>
const close = () => {
  if (!modal.value) return
  modal.value.close()
  onClose()
}

effect(() => {
  isOpen?.value ? modal.value.showModal() : close()
})

const onClick = (event: MouseEvent) => {
  if (inBounds(modal.value)(event)) return
  close()
}
</script>
<template>
  <dialog ref="modal" @click="onClick" :class="className">
    <slot></slot>
  </dialog>
</template>

// apps/solid/src/lib/components/modal.tsx
import {
  type Dialog,
  inBounds,
} from 'core/lib/components/modal'
import { IO } from 'fp-ts/IO'
import {
  Accessor,
  ParentComponent,
  createEffect,
} from 'solid-js'

interface Props {
  className: string
  isOpen: Accessor<boolean>
  onClose: IO<void>
}

const _: ParentComponent<Props> = ({
  children,
  className,
  isOpen,
  onClose,
}) => {
  let modal = (<></>) as Dialog
  const close = () => {
    modal.close()
    onClose()
  }

  createEffect(() =>
    isOpen() ? modal.showModal() : close()
  )

  const onClick = (event: MouseEvent) => {
    if (inBounds(modal)(event)) return
    close()
  }

  return (
    <dialog ref={modal} onClick={onClick} class={className}>
      <div>{children}</div>
    </dialog>
  )
}

export default _
