// packages/solid/src/lib/components/modal.tsx
import { type Dialog, targets } from 'core/lib/components/modal'
import { IO } from 'fp-ts/IO'
import { Component, createEffect } from 'solid-js'
import { Accessor } from 'solid-js'

type Props = {
  children: string
  isOpen: Accessor<boolean>
  onClose: IO<void>
}

const _: Component<Props> = ({ children, isOpen, onClose }) => {
  let modal = (<></>) as Dialog
  const close = () => {
    modal.close()
    onClose()
  }

  createEffect(() => (isOpen() ? modal.showModal() : close()))

  const onClick = (event: MouseEvent) =>
    targets(modal)(event) ? close() : null

  return (
    <dialog ref={modal} onClick={onClick}>
      <div>{children}</div>
    </dialog>
  )
}

export default _

// packages/svelte/src/lib/components/modal.svelte
<script lang="ts">
  import {
    type Dialog,
    inBounds,
  } from 'core/lib/components/modal'
  import type { IO } from 'fp-ts/IO'
  import type { Readable } from 'svelte/store'
  import type { Snippet } from 'svelte'

  interface Props {
    children: Snippet<[]>
    className?: string
    isOpen: Readable<boolean>
    onClose: IO<void>
  }
  const { children, className, isOpen, onClose }: Props = $props()
  let modal: Dialog
  const close = () => {
    if (!modal) return
    modal.close()
    onClose()
  }

  $effect(() => {
    $isOpen ? modal.showModal() : close()
  })

  const onclick = (event: MouseEvent) => {
    if (inBounds(modal)(event)) return
    close()
  }
</script>

  <dialog
    bind:this={modal}
    {onclick}
    class={className}
    role="none"
  >{@render children()}</dialog>
