// apps/react/src/App/Hint/Digit.tsx
import { elem } from 'fp-ts/Array'
import { Eq as nEq } from 'fp-ts/number'
import { Digit } from 'core/interface/types'
import { style } from 'core/style'

type Props = {
  digit: Digit
  hint: Digit[]
}

const _ = ({ digit, hint }: Props) => (
  <div
    className={
      elem(nEq)(digit)(hint)
        ? style.hint.number.on
        : style.hint.number.off
    }
  >
    {digit}
  </div>
)

export default _

// packages/svelte/src/app/hint/Digit.svelte
<script lang="ts">
  import { style } from 'core/style'
  import type { Digit } from 'core/interface/types'
  import { elem } from 'fp-ts/Array'
  import { Eq as nEq } from 'fp-ts/number'

  type Props = { digit: Digit; hint: Digit[] }
  let { digit, hint }: Props = $props()
  const className = $derived(
    elem(nEq)(digit)(hint)
      ? style.hint.number.on
      : style.hint.number.off
  )
</script>

<div class={className}>
  {digit}
</div>
