// packages/react/src/lib/hooks/resume.ts
import { Stopwatch } from './stopwatch'
import { useEffect, useState } from 'react'

export const useResume = (
  { isRunning, toggleTimer }: Stopwatch,
  isOpen: boolean
) => {
  const [resume, setResume] = useState(false)
  useEffect(() => {
    if (isOpen && isRunning) {
      toggleTimer()
      setResume(true)
    }

    if (!isOpen && resume) {
      toggleTimer()
      setResume(false)
    }
  }, [isOpen])
}

// packages/solid/src/lib/hooks/resume.ts
import {
  Accessor,
  createEffect,
  createSignal,
} from 'solid-js'
import { Stopwatch } from './stopwatch'

export const useResume = (
  { isRunning, toggleTimer }: Stopwatch,
  isOpen: Accessor<boolean>
) => {
  const [resume, setResume] = createSignal(false)
  createEffect(() => {
    if (isOpen() && isRunning()) {
      toggleTimer()
      setResume(() => true)
    }

    if (!isOpen() && resume()) {
      toggleTimer()
      setResume(() => false)
    }
  })
}
