// apps/svelte/src/app/board/Board.svelte
<script lang="ts">
  import { mouseOutsideEvent } from 'core/events/board'
  import { regionIndicies } from 'core/interface/toolkit'
  import { style } from 'core/style'
  import { pipe } from 'fp-ts/function'
  import { dispatchFold } from 'apps/svelte/store'
  import Region from './Region.svelte'

  const setMouseOutside =
    (value: boolean) =>
    (event: MouseEvent | FocusEvent) => {
      const payload = { value }
      const eventData = { event, payload }
      pipe(eventData, mouseOutsideEvent, dispatchFold)
    }
  const onmouseout = setMouseOutside(true)
  const onmouseover = setMouseOutside(false)
</script>

<div
  class={style.board.root}
  {onmouseout}
  onblur={onmouseout}
  {onmouseover}
  onfocus={onmouseover}
  role="none"
>
  {#each regionIndicies as region}
    <Region {region} />
  {/each}
</div>

// packages/solid/src/App/Board/index.tsx
import { For } from 'solid-js'
import { pipe } from 'fp-ts/function'
import { mouseOutsideEvent } from 'core/events/board'
import { regionIndicies } from 'core/interface/toolkit'
import { style } from 'core/style'
import { dispatchFold } from '~/store'
import Region from './Region'

const _ = () => {
  const setMouseOutside = (value: boolean) => (event: MouseEvent) => {
    const payload = { value }
    const eventData = { event, payload }
    pipe(eventData, mouseOutsideEvent, dispatchFold)
  }

  return (
    <div
      class={style.board.root}
      onMouseOut={setMouseOutside(true)}
      onMouseOver={setMouseOutside(false)}
    >
      <For each={regionIndicies}>
        {(region) => <Region region={region} />}
      </For>
    </div>
  )
}

export default _
