// packages/svelte/src/app/menu/Autosolve.svelte
<script lang="ts">
  import Fa from 'svelte-fa'
  import { faHatWizard } from '@fortawesome/free-solid-svg-icons'
  import { toggle } from 'core/actions'
  import { autosolveLens } from 'core/interface/optics'
  import { style } from 'core/style'
  import { dispatch, state } from '~/store'

  const onClick = () => dispatch(toggle({ lens: autosolveLens }))
  const { toggles } = state
</script>

<div
  class={$toggles.autosolve
    ? style.menu.btns.on
    : style.menu.btns.off}
  on:click={onClick}
>
  <Fa icon={faHatWizard} size="lg" />
</div>

// packages/react/src/App/Menu/Autosolve.tsx
import {
  faHatWizard
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { toggle } from 'core/actions'
import { autosolveLens } from 'core/interface/optics'
import { style } from 'core/style'
import { useStore } from '~/store'

const Autosolve = () => {
  const { state, dispatch } = useStore()
  const className = state.toggles.autosolve
    ? style.menu.btns.on
    : style.menu.btns.off
  const onClick = () =>
    dispatch(toggle({ lens: autosolveLens }))
  return (
    <div className={className} onClick={onClick}>
      <FontAwesomeIcon icon={faHatWizard} size="xl"/>
    </div>
  )
}

export default Autosolve
