// packages/vue/src/app/menu/Edit.vue
<script setup lang="ts">
import { clearBoard, lockBoard } from 'core/actions'
import { style } from 'core/style'
import { faLock, faPlus } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { useDisclosure } from '~/lib/hooks'
import { useState } from '~/store'

const disclosure = useDisclosure()
const state = useState()
const onClick = () => {
  disclosure.isOpen.value
    ? state.dispatch(lockBoard)
    : state.dispatch(clearBoard)
  disclosure.onToggle()
}
</script>

<template>
  <div :class="style.menu.btns.off" @click="onClick">
    <font-awesome-icon v-if="disclosure.isOpen.value" :icon="faLock" size="xl"/>
    <font-awesome-icon v-else :icon="faPlus" size="xl"/>
  </div>
</template>

// packages/react/src/App/Menu/Edit.tsx
import {
  faLock,
  faPlus,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { clearBoard, lockBoard } from 'core/actions'
import { style } from 'core/style'
import { useDisclosure } from '~/lib/hooks'
import { useStore } from '~/store'

const Edit = () => {
  const { dispatch } = useStore()
  const { isOpen, onToggle } = useDisclosure()
  const className = style.menu.btns.off
  const onClick = () => {
    isOpen ? dispatch(lockBoard) : dispatch(clearBoard)
    onToggle()
  }
  return (
    <div className={className} onClick={onClick}>
      {isOpen ? (
        <FontAwesomeIcon icon={faLock} size="xl" />
      ) : (
        <FontAwesomeIcon icon={faPlus} size="xl" />
      )}
    </div>
  )
}

export default Edit
