// packages/vue/src/app/menu/StartOver.vue
<script setup lang="ts">
import { resetBoard } from 'core/actions'
import { style } from 'core/style'
import { faRotate } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { useState } from '~/store'

const state = useState()
const onClick = () => state.dispatch(resetBoard)
</script>

<template>
  <div :class="style.menu.btns.off" @click="onClick">
    <font-awesome-icon :icon="faRotate" size="xl" />
  </div>
</template>

// packages/react/src/App/Menu/StartOver.tsx
import { faRotate } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { resetBoard } from 'core/actions'
import { style } from 'core/style'
import { useStore } from '~/store'

const StartOver = () => {
  const { dispatch } = useStore()
  const onClick = () => dispatch(resetBoard)
  return (
    <div className={style.menu.btns.off} onClick={onClick}>
      <FontAwesomeIcon icon={faRotate} size="xl" />
    </div>
  )
}

export default StartOver
