// apps/svelte/src/app/menu/Timer.svelte
<script lang="ts">
  import Fa from 'svelte-fa'
  import {
    faPause,
    faPlay,
    faRotateLeft,
  } from '@fortawesome/free-solid-svg-icons'
  import { style } from 'core/style'
  import { getContext } from 'svelte'
  import type { Stopwatch } from 'apps/svelte/lib/hooks'
  
  const { time, isRunning, resetTimer, toggleTimer } =
    getContext<Stopwatch>('stopwatch')
</script>

<div class={style.menu.timer.root}>
  <p class={style.menu.timer.txt}>{$time}</p>
  <button class={style.menu.timer.btn} onclick={toggleTimer}>
    {#if $isRunning}
      <Fa icon={faPause} size="sm" />
    {:else}
      <Fa icon={faPlay} size="sm" />
    {/if}
  </button>
  <button class={style.menu.timer.btn} onclick={resetTimer}>
    <Fa icon={faRotateLeft} size="sm" />
  </button>
</div>

// packages/react/src/App/Menu/Timer.tsx
import {
  faPlay,
  faPause,
  faRotateLeft,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { style } from 'core/style'
import { Stopwatch } from '~/lib/hooks'

const Timer = ({
  stopwatch: { time, resetTimer, toggleTimer, isRunning },
}: {
  stopwatch: Stopwatch
}) => (
  <div className={style.menu.timer.root}>
    <p className={style.menu.timer.txt}>{time}</p>
    <div
      className={style.menu.timer.btn}
      onClick={toggleTimer}
    >
      {isRunning ? (
        <FontAwesomeIcon icon={faPause} size="sm" />
      ) : (
        <FontAwesomeIcon icon={faPlay} size="sm" />
      )}
    </div>
    <div
      className={style.menu.timer.btn}
      onClick={resetTimer}
    >
      <FontAwesomeIcon icon={faRotateLeft} size="sm" />
    </div>
  </div>
)

export default Timer
