// packages/svelte/src/app/Confetti.svelte
<script lang="ts">
  import P5 from 'p5'
  import { sketch } from 'confetti/sketch'
  import { style } from 'core/style'
  import { state } from '~/store'
  import { onDestroy } from 'svelte'

  let p5: P5
  let canvas: HTMLElement
  const { isSolved } = state

  $: {
    if ($isSolved) {
      p5 = new P5(sketch(document.body), canvas)
    } else {
      p5?.remove()
    }
  }

  onDestroy(() => p5?.remove())
</script>

<div bind:this={canvas} class={style.menu.confetti} />

// packages/solid/src/App/Confetti.tsx
import P5 from 'p5'
import { createMemo, onCleanup } from 'solid-js'
import { sketch } from 'confetti/sketch'
import { style } from 'core/style'
import { state } from '~/store'

const _ = () => {
  let p5: P5

  const root = (<div class={style.menu.confetti} />) as HTMLElement

  createMemo(() => {
    if (state.isSolved) {
      p5 = new P5(sketch(document.body), root)
    } else {
      p5?.remove()
    }
  })

  onCleanup(() => {
    p5?.remove()
  })

  return root
}

export default _
