// apps/react/src/store.tsx
import type { Action } from 'core/actions/types'
import { ActionType } from 'core/actions/types'
import { initialState } from 'core/interface/init'
import {
  autosolve,
  clearSelection,
  clearBoard,
  lockBoard,
  selectNumber,
  puzzleToBoard,
  resetBoard,
  selectAll,
  selectCell,
  setToggle,
  toggle,
  updateBig,
  updateSmall,
} from 'core/model'
import type { State } from 'core/interface/types'
import { map } from 'fp-ts/Array'
import { constVoid, pipe } from 'fp-ts/function'
import { fold, Option } from 'fp-ts/Option'
import {
  createContext,
  useContext,
  useReducer,
  Reducer,
  PropsWithChildren,
} from 'react'

const reducer: Reducer<State, Action> = (
  { board, selectedNumber, toggles },
  action
) => {
  switch (action.type) {
    case ActionType.AUTOSOLVE:
      return {
        board: autosolve(action.payload)(board),
        selectedNumber,
        toggles,
      }
    case ActionType.SET_PUZZLE:
      return {
        board: puzzleToBoard(action.payload.puzzle),
        selectedNumber,
        toggles,
      }
    case ActionType.CLEAR_SELECTION:
      return {
        board: clearSelection(board),
        selectedNumber: 0,
        toggles,
      }
    case ActionType.CLEAR_BOARD:
      return {
        board: clearBoard,
        selectedNumber,
        toggles,
      }
    case ActionType.LOCK_BOARD:
      return {
        board: lockBoard(board),
        selectedNumber,
        toggles,
      }
    case ActionType.SELECT_NUMBER:
      return {
        board: pipe(
          board,
          clearSelection,
          selectNumber(action.payload)
        ),
        selectedNumber: action.payload.value,
        toggles,
      }
    case ActionType.RESET_BOARD:
      return {
        board: resetBoard(board),
        selectedNumber,
        toggles,
      }
    case ActionType.SELECT_ALL:
      return {
        board: selectAll(board),
        selectedNumber,
        toggles,
      }
    case ActionType.SELECT_CELL:
      return {
        board: selectCell(action.payload)(board),
        selectedNumber: 0,
        toggles,
      }
    case ActionType.UPDATE_BIG:
      return {
        board: updateBig(action.payload)(board),
        selectedNumber,
        toggles,
      }
    case ActionType.UPDATE_SMALL:
      return {
        board: updateSmall(action.payload)(board),
        selectedNumber,
        toggles,
      }
    case ActionType.TOGGLE:
      return {
        board,
        selectedNumber,
        toggles: toggle(action.payload)(toggles),
      }
    case ActionType.SET_TOGGLE:
      return {
        board,
        selectedNumber,
        toggles: setToggle(action.payload)(toggles),
      }
    default:
      return { board, selectedNumber, toggles }
  }
}

const logDispatchError = () =>
  console.error(
    'Failed to read dispatch function from StateProvider.'
  )

const StoreContext = createContext({
  state: initialState,
  dispatch: (_: Action) => logDispatchError(),
  dispatchMap: (_: Action[]) => logDispatchError(),
  dispatchFold: (_: Option<Action[]>) => logDispatchError(),
})

const StoreProvider = ({ children }: PropsWithChildren) => {
  const [state, dispatch] = useReducer<
    Reducer<State, Action>
  >(reducer, initialState)
  const dispatchMap = map(dispatch)
  const dispatchFold = fold(constVoid, dispatchMap)

  return (
    <StoreContext.Provider
      value={{
        state,
        dispatch,
        dispatchMap,
        dispatchFold,
      }}
    >
      {children}
    </StoreContext.Provider>
  )
}

const useStore = () => useContext(StoreContext)

export { useStore, StoreProvider }

// packages/solid/src/store.ts
import { map } from 'fp-ts/Array'
import { constVoid } from 'fp-ts/function'
import { fold } from 'fp-ts/Option'
import { ActionType } from 'core/actions/types'
import {
  canAutosolve,
  getHints,
  getSelectedOption,
  isSolved,
} from 'core/computed'
import { initialState } from 'core/interface/init'
import {
  Dispatch,
  DispatchFold,
  DispatchMap,
  Hints,
  Selection,
  State,
} from 'core/interface/types'
import {
  autosolve,
  clearSelection,
  clearBoard,
  lockBoard,
  selectNumber,
  puzzleToBoard,
  resetBoard,
  selectAll,
  selectCell,
  setToggle,
  toggle,
  updateBig,
  updateSmall,
} from 'core/model'
import { createStore } from 'solid-js/store'

export interface StateWithGetters extends State {
  hints: Hints
  selection: Selection
  isSolved: boolean
  canAutosolve: boolean
}

const init: StateWithGetters = {
  ...initialState,
  get hints() {
    return getHints(this.board)
  },
  get selection() {
    return getSelectedOption(this.board)
  },
  get isSolved() {
    return isSolved(this.board)
  },
  get canAutosolve() {
    return canAutosolve(this)
  },
}

const [state, setState] = createStore(init)

const dispatch: Dispatch = (action) => {
  switch (action.type) {
    case ActionType.AUTOSOLVE:
      setState('board', autosolve(action.payload))
      break
    case ActionType.SET_PUZZLE:
      setState('board', puzzleToBoard(action.payload.puzzle))
      break
    case ActionType.CLEAR_SELECTION:
      setState('selectedNumber', 0)
      setState('board', clearSelection)
      break
    case ActionType.CLEAR_BOARD:
      setState('board', clearBoard)
      break
    case ActionType.LOCK_BOARD:
      setState('board', lockBoard)
      break
    case ActionType.SELECT_NUMBER:
      setState('board', clearSelection)
      setState('selectedNumber', action.payload.value)
      setState('board', selectNumber(action.payload))
      break
    case ActionType.RESET_BOARD:
      setState('board', resetBoard)
      break
    case ActionType.SELECT_ALL:
      setState('board', selectAll)
      break
    case ActionType.SELECT_CELL:
      setState('selectedNumber', 0)
      setState('board', selectCell(action.payload))
      break
    case ActionType.UPDATE_BIG:
      setState('board', updateBig(action.payload))
      break
    case ActionType.UPDATE_SMALL:
      setState('board', updateSmall(action.payload))
      break
    case ActionType.TOGGLE:
      setState('toggles', toggle(action.payload))
      break
    case ActionType.SET_TOGGLE:
      setState('toggles', setToggle(action.payload))
      break
    default:
      break
  }
}

const dispatchMap: DispatchMap = map(dispatch)
const dispatchFold: DispatchFold = fold(constVoid, dispatchMap)

export { dispatch, dispatchFold, dispatchMap, state }
