// packages/svelte/src/app/Confetti.svelte
<script lang="ts">
  import P5 from 'p5'
  import { sketch } from 'confetti/sketch'
  import { style } from 'core/style'
  import { state } from '~/store'
  import { onDestroy } from 'svelte'

  let p5: P5
  let canvas: HTMLElement
  const { isSolved } = state

  $: {
    if ($isSolved) {
      p5 = new P5(sketch(document.body), canvas)
    } else {
      p5?.remove()
    }
  }

  onDestroy(() => p5?.remove())
</script>

<div bind:this={canvas} class={style.menu.confetti} />

// packages/vue/src/app/Confetti.vue
<script setup lang="ts">
import P5 from 'p5'
import { sketch } from 'confetti/sketch'
import { style } from 'core/style'
import { useState } from '~/store'
import { effect, onUnmounted, ref } from 'vue'

let p5: P5
let canvas = ref()
const state = useState()

effect(() => {
  if (state.isSolved) {
    p5 = new P5(sketch(document.body), canvas.value)
  } else {
    p5?.remove()
  }
})

onUnmounted(() => p5?.remove())
</script>

<template>
  <div ref="canvas" :class="style.menu.confetti" />
</template>
