// apps/solid/src/App/Board/Cell.tsx
import { createMemo, Component, Show } from 'solid-js'
import { style } from 'core/style'
import { isNonZero } from 'fns'
import {
  mouseEnterEvent,
  mouseDownEvent,
} from 'core/events/cell'
import { state } from 'apps/solid/store'
import { useEvent } from 'apps/solid/lib/hooks'

const _: Component<{ i: number }> = ({ i }) => {
  const cell = createMemo(() => state.board[i])
  const onMouseDown = useEvent(mouseDownEvent)({
    cell: cell(),
  })

  const onMouseEnter = useEvent(mouseEnterEvent)({
    cell: cell(),
    toggles: state.toggles,
  })

  return (
    <div
      class={
        style.board.cell[cell().editable][cell().decoration]
      }
      onMouseDown={onMouseDown}
      onMouseEnter={onMouseEnter}
    >
      <Show when={isNonZero(cell().value)}>
        <p>{cell().value}</p>
      </Show>
    </div>
  )
}

export default _

// apps/react/src/App/Board/Cell.tsx
import {
  mouseEnterEvent,
  mouseDownEvent,
} from 'core/events/cell'
import { style } from 'core/style'
import { isNonZero } from 'fns'
import { useEvent } from 'apps/react/lib/hooks'
import { useStore } from 'apps/react/store'

const Cell = ({ i }: { i: number }) => {
  const { state } = useStore()
  const { board, toggles } = state
  const cell = board[i]
  const className =
    style.board.cell[cell.editable][cell.decoration]
  const onMouseDown = useEvent(mouseDownEvent)({ cell })
  const onMouseEnter = useEvent(mouseEnterEvent)({
    cell,
    toggles,
  })

  return (
    <div
      className={className}
      onMouseDown={onMouseDown}
      onMouseEnter={onMouseEnter}
    >
      <p>{isNonZero(cell.value) && cell.value}</p>
    </div>
  )
}

export default Cell
