// apps/vue/src/app/board/Cell.vue
<script setup lang="ts">
import { mouseEnterEvent, mouseDownEvent } from 'core/events/cell'
import { style } from 'core/style'
import { isNonZero } from 'fns'
import { computed } from 'vue'
import { useEvent } from 'apps/vue/lib/hooks'
import { useState } from 'apps/vue/store'

const { i } = defineProps({ i: { type: Number, required: true } })
const state = useState()
const cell = computed(() => state.board[i])
const onMouseDown = useEvent(mouseDownEvent)({ cell: cell.value })
const onMouseEnter = useEvent(mouseEnterEvent)({ cell: cell.value, toggles: state.toggles })
</script>

<template>
  <div
    :class="style.board.cell[cell.editable][cell.decoration]"
    @mouseenter="onMouseEnter"
    @mousedown="onMouseDown"
  >
    <p v-show="isNonZero(cell.value)">{{ cell.value }}</p>
  </div>
</template>

// apps/react/src/App/Board/Cell.tsx
import {
  mouseEnterEvent,
  mouseDownEvent,
} from 'core/events/cell'
import { style } from 'core/style'
import { isNonZero } from 'fns'
import { useEvent } from 'apps/react/lib/hooks'
import { useStore } from 'apps/react/store'

const Cell = ({ i }: { i: number }) => {
  const { state } = useStore()
  const { board, toggles } = state
  const cell = board[i]
  const className =
    style.board.cell[cell.editable][cell.decoration]
  const onMouseDown = useEvent(mouseDownEvent)({ cell })
  const onMouseEnter = useEvent(mouseEnterEvent)({
    cell,
    toggles,
  })

  return (
    <div
      className={className}
      onMouseDown={onMouseDown}
      onMouseEnter={onMouseEnter}
    >
      <p>{isNonZero(cell.value) && cell.value}</p>
    </div>
  )
}

export default Cell
