// packages/react/src/App/Menu/ColorMode.tsx
import {
  faMoon,
  faSun,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { toggle } from 'core/actions'
import { darkModeLens } from 'core/interface/optics'
import { style } from 'core/style'
import { useStore } from '~/store'

const ColorMode = () => {
  const { state, dispatch } = useStore()
  const className = style.menu.btns.off
  const onClick = () =>
    dispatch(toggle({ lens: darkModeLens }))
  return (
    <div className={className} onClick={onClick}>
      {state.toggles.darkMode ? (
        <FontAwesomeIcon icon={faSun} size="xl" />
      ) : (
        <FontAwesomeIcon icon={faMoon} size="xl" />
      )}
    </div>
  )
}

export default ColorMode

// packages/svelte/src/app/menu/ColorMode.svelte
<script lang="ts">
  import Fa from 'svelte-fa'
  import { faMoon, faSun } from '@fortawesome/free-solid-svg-icons'
  import { toggle } from 'core/actions'
  import { darkModeLens } from 'core/interface/optics'
  import { style } from 'core/style'
  import { dispatch, state } from '~/store'

  const onClick = () => dispatch(toggle({ lens: darkModeLens }))
  const {toggles} = state
</script>

<div class={style.menu.btns.off} on:click={onClick}>
    {#if $toggles.darkMode}
    <Fa icon={faSun} size="lg" />
  {:else}
    <Fa icon={faMoon} size="lg" />
  {/if}
  </div>
