// packages/react/src/App/Menu/StartOver.tsx
import { faRotate } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { resetBoard } from 'core/actions'
import { style } from 'core/style'
import { useStore } from '~/store'

const StartOver = () => {
  const { dispatch } = useStore()
  const onClick = () => dispatch(resetBoard)
  return (
    <div className={style.menu.btns.off} onClick={onClick}>
      <FontAwesomeIcon icon={faRotate} size="xl" />
    </div>
  )
}

export default StartOver

// packages/svelte/src/app/menu/StartOver.svelte
<script lang="ts">
  import Fa from 'svelte-fa'
  import { faRotate } from '@fortawesome/free-solid-svg-icons'
  import { resetBoard } from 'core/actions'
  import { style } from 'core/style'
  import { dispatch } from '~/store'

  const onClick = () => dispatch(resetBoard)
</script>

<div class={style.menu.btns.off} on:click={onClick}>
  <Fa icon={faRotate} size="lg" />
</div>
