// packages/react/src/App/Menu/ColorMode.tsx
import {
  faMoon,
  faSun,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { toggle } from 'core/actions'
import { darkModeLens } from 'core/interface/optics'
import { style } from 'core/style'
import { useStore } from '~/store'

const ColorMode = () => {
  const { state, dispatch } = useStore()
  const className = style.menu.btns.off
  const onClick = () =>
    dispatch(toggle({ lens: darkModeLens }))
  return (
    <div className={className} onClick={onClick}>
      {state.toggles.darkMode ? (
        <FontAwesomeIcon icon={faSun} size="xl" />
      ) : (
        <FontAwesomeIcon icon={faMoon} size="xl" />
      )}
    </div>
  )
}

export default ColorMode

// packages/vue/src/app/menu/ColorMode.vue
<script setup lang="ts">
import { toggle } from 'core/actions'
import { darkModeLens } from 'core/interface/optics'
import { style } from 'core/style'
import { faMoon, faSun } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { useState } from '~/store'

const state = useState()
const onClick = () => state.dispatch(toggle({ lens: darkModeLens }))
</script>

<template>
  <div :class="style.menu.btns.off" @click="onClick">
    <font-awesome-icon
      v-if="state.toggles.darkMode"
      :icon="faSun"
      size="xl"
    />
    <font-awesome-icon v-else :icon="faMoon" size="xl" />
  </div>
</template>
