// packages/svelte/src/app/menu/Menu.svelte
<script lang="ts">
  import { style } from 'core/style'
  import { onMount, setContext } from 'svelte'
  import { useStopwatch } from '~/lib/hooks'
  import { state } from '~/store'
  import Autosolve from './Autosolve.svelte'
  import ColorMode from './ColorMode.svelte'
  import Edit from './Edit.svelte'
  import Help from './Help.svelte'
  import StartOver from './StartOver.svelte'
  import Timer from './Timer.svelte'

  const stopwatch = useStopwatch()
  const { isRunning } = stopwatch
  const { isSolved } = state
  setContext('stopwatch', stopwatch)
  onMount(stopwatch.startTimer)
  $effect(() => {
    if ($isSolved && $isRunning) {
      stopwatch.stopTimer()
    }
  })
</script>

<div class={style.menu.root}>
  <Timer />
  <div class={style.menu.btns.root}>
    <StartOver />
    <Edit />
    <Autosolve />
    <ColorMode />
    <Help />
  </div>
</div>

// packages/vue/src/app/menu/Menu.vue
<script setup lang="ts">
import { style } from 'core/style'
import { effect, onMounted, provide } from 'vue'
import { useStopwatch } from '~/lib/hooks'
import { useState } from '~/store'
import Autosolve from './Autosolve.vue'
import ColorMode from './ColorMode.vue'
import Edit from './Edit.vue'
import Help from './Help.vue'
import StartOver from './StartOver.vue'
import Timer from './Timer.vue'

const stopwatch = useStopwatch()
const state = useState()
provide('stopwatch', stopwatch)
onMounted(stopwatch.startTimer)
effect(() => {
  if (!state.isSolved) return
  if (!stopwatch.isRunning) return
  stopwatch.stopTimer()
})
</script>

<template>
  <div :class="style.menu.root">
    <Timer />
    <div :class="style.menu.btns.root">
      <StartOver />
      <Edit />
      <Autosolve />
      <ColorMode />
      <Help />
    </div>
  </div>
</template>
