// packages/react/src/App/Menu/Timer.tsx
import {
  faPlay,
  faPause,
  faRotateLeft,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { style } from 'core/style'
import { Stopwatch } from '~/lib/hooks'

const Timer = ({
  stopwatch: { time, resetTimer, toggleTimer, isRunning },
}: {
  stopwatch: Stopwatch
}) => (
  <div className={style.menu.timer.root}>
    <p className={style.menu.timer.txt}>{time}</p>
    <div
      className={style.menu.timer.btn}
      onClick={toggleTimer}
    >
      {isRunning ? (
        <FontAwesomeIcon icon={faPause} size="sm" />
      ) : (
        <FontAwesomeIcon icon={faPlay} size="sm" />
      )}
    </div>
    <div
      className={style.menu.timer.btn}
      onClick={resetTimer}
    >
      <FontAwesomeIcon icon={faRotateLeft} size="sm" />
    </div>
  </div>
)

export default Timer

// packages/vue/src/app/menu/Timer.vue
<script setup lang="ts">
import { style } from 'core/style'
import {
  faPause,
  faPlay,
  faUndoAlt,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { inject } from 'vue'
import type { Stopwatch } from '~/lib/hooks'

const stopwatch = inject<Stopwatch>(
  'stopwatch'
) as Stopwatch
</script>

<template>
  <div :class="style.menu.timer.root">
    <p :class="style.menu.timer.txt">
      {{ stopwatch.time.value.replace('"', '') }}
    </p>
    <div
      :class="style.menu.timer.btn"
      @click="stopwatch.toggleTimer"
    >
      <font-awesome-icon
        size="sm"
        :icon="stopwatch.isRunning.value ? faPause : faPlay"
      />
    </div>
    <div
      :class="style.menu.timer.btn"
      @click="stopwatch.resetTimer"
    >
      <font-awesome-icon size="sm" :icon="faUndoAlt" />
    </div>
  </div>
</template>
