// apps/svelte/src/app/menu/Edit.svelte
<script lang="ts">
  import Fa from 'svelte-fa'
  import { faLock, faPlus } from '@fortawesome/free-solid-svg-icons'
  import { clearBoard, lockBoard } from 'core/actions'
  import { style } from 'core/style'
  import { useDisclosure } from 'apps/svelte/lib/hooks'
  import { dispatch } from 'apps/svelte/store'

  const { isOpen, onToggle } = useDisclosure()
  const onclick = () => {
    $isOpen ? dispatch(lockBoard) : dispatch(clearBoard)
    onToggle()
  }
</script>

<button class={style.menu.btns.off} {onclick}>
  {#if $isOpen}
    <Fa icon={faLock} size="lg" />
  {:else}
    <Fa icon={faPlus} size="lg" />
  {/if}
</button>

// apps/react/src/App/Menu/Edit.tsx
import {
  faLock,
  faPlus,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { clearBoard, lockBoard } from 'core/actions'
import { style } from 'core/style'
import { useDisclosure } from 'apps/react/lib/hooks'
import { useStore } from 'apps/react/store'

const Edit = () => {
  const { dispatch } = useStore()
  const { isOpen, onToggle } = useDisclosure()
  const className = style.menu.btns.off
  const onClick = () => {
    isOpen ? dispatch(lockBoard) : dispatch(clearBoard)
    onToggle()
  }
  return (
    <div className={className} onClick={onClick}>
      {isOpen ? (
        <FontAwesomeIcon icon={faLock} size="xl" />
      ) : (
        <FontAwesomeIcon icon={faPlus} size="xl" />
      )}
    </div>
  )
}

export default Edit
