// apps/solid/src/App/Board/index.tsx
import { mouseOutsideEvent } from 'core/events/board'
import { regionIndicies } from 'core/interface/toolkit'
import { For } from 'solid-js'
import { style } from 'core/style'
import { useEvent } from 'apps/solid/lib/hooks'
import Region from './Region'

const _ = () => {
  const onMouseOut = useEvent(mouseOutsideEvent)({value: true})
  const onMouseOver = useEvent(mouseOutsideEvent)({value: false})

  return (
    <div
      class={style.board.root}
      onMouseOut={onMouseOut}
      onMouseOver={onMouseOver}
    >
      <For each={regionIndicies}>
        {(region) => <Region region={region} />}
      </For>
    </div>
  )
}

export default _

// apps/vue/src/app/board/Board.vue
<script setup lang="ts">
import { mouseOutsideEvent } from 'core/events/board'
import { regionIndicies } from 'core/interface/toolkit'
import { style } from 'core/style'
import { useEvent } from 'apps/vue/lib/hooks'
import Region from './Region.vue'

const setMouseOutside = useEvent(mouseOutsideEvent)
const onMouseOut = setMouseOutside({ value: true })
const onMouseOver = setMouseOutside({ value: false })
</script>

<template>
  <div
    :class="style.board.root"
    @mouseout="onMouseOut"
    @mouseover="onMouseOver"
  >
    <Region
      v-for="(region, i) in regionIndicies"
      :region="region"
      :key="i"
    />
  </div>
</template>
